Added pre-scripts

diff --git a/_pkg-functions.in b/_pkg-functions.in
--- a/_pkg-functions.in
+++ b/_pkg-functions.in
@@ -58,7 +58,17 @@ _unwrite_schema_config() {
   fi
 }
 
-
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 postinst() {
     local distr=${1:-$DISTR}
     local action=${2:-$ACTION}
@@ -86,6 +96,18 @@ postinst() {
     esac
 }
 
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 postrm() {
     local distr=${1:-$DISTR}
     local action=${2:-$ACTION}
@@ -106,3 +128,66 @@ postrm() {
         ;;
     esac
 }
+
+# summary of how this script can be called:
+#        * <new-preinst> `install'
+#        * <new-preinst> `install' <old-version>
+#        * <new-preinst> `upgrade' <old-version>
+#        * <old-preinst> `abort-upgrade' <new-version>
+#
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+preinst() {
+    local distr=${1:-$DISTR}
+    local action=${2:-$ACTION}
+
+    case "$action" in
+        install)
+        ;;
+        upgrade)
+        ;;
+        abort-upgrade|abort-remove|abort-deconfigure)
+        ;;
+        null)
+            exit 0
+        ;;
+        *)
+            echo "preinst called with unknown argument \`$@'" >&2
+            exit 1
+        ;;
+    esac
+}
+
+
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see /usr/doc/packaging-manual/
+prerm() {
+    local distr=${1:-$DISTR}
+    local action=${2:-$ACTION}
+    local version=$3
+
+    case "$action" in
+     remove)
+      if [ -z "$vesrion" ] ; then
+        uninstall || exit $?
+      fi
+     ;;
+     upgrade|deconfigure)
+     ;;
+     failed-upgrade)
+     ;;
+     *)
+         echo "prerm called with unknown arguments \`$@'" >&2
+         exit 0
+     ;;
+ esac
+}
+
+
